version: '3'
services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm run start
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:3
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    ports:
      - 27017:27017
    restart: always

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm run start-bot
