version: '3'
services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
  mongodb:
    image: mongo:3
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    ports:
      - 27017:27017