version: '3'
services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    environment:
      - START_COMMAND=npm run start
  
  mongodb:
    image: mongo:3
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    ports:
      - 27017:27017
    restart: always

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - START_COMMAND=npm run start-bot
    env_file:
      - ./env_file.txt
